project:
  type: default
  output-dir: presos
  resources:
  - "pictures/*"
  
  render: 
    - posts//*.qmd
    - posts/tutorials/en/*.ipynb

format:
  revealjs:
    theme: [dark, preso-whiteboard-halfwidth.scss]
    execute: true
    code-fold: true
    code-tools: true
    freeze: auto
    chalkboard: true

variables:
  presentation: true