project:
  type: default
  output-dir: presos
  

  render: 
    - posts/video/fr/*.qmd
    - posts/video/fr/*.ipynb
    - posts/video/en/*.qmd
    - posts/video/en/*.ipynb

format:
  revealjs:
    execute: True
    theme: [simple, preso-backbboard-halfwidth.scss]
