baseurl = "https://portfolio-geek.com"
languageCode = "en-us"
title = "Technology and Portfolio Construction"
pygmentsCodefences = true
pygmentsStyle = "pygments"

[params]
    dateFormat = "Jan 2, 2006"
    homeText =  "Notepad of a geek in finance"

[permalinks]
    blog = "/:filename/"

[taxonomies]
    tag = "tags"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3
