---
title: "17/07/2024:  Economics, Indexing, Quant and Coding Links"
page-layout: full
title-block-banner: true
---


Portfolio Construction


|Title|Source|Summary|
|-----|-------|----------|
|[Pragmatic Asset Allocation from Vojtko and Javorská of Quantpedia](https://allocatesmartly.com/pragmatic-asset-allocation-from-vojtko-and-javorska-of-quantpedia/)|Quantpedia|Pragmatic Asset Allocation is a tactical strategy that adjusts the portfolio based on market conditions while also ensuring tax efficiency. It uses the yield curve inversion and price change indicators to allocate between risk and defensive assets. |
|[Can we please stop selling these products](https://klementoninvesting.substack.com/p/can-we-please-stop-selling-these)|Klement on Investing|Pragmatic Asset Allocation is a tactical strategy that adjusts the portfolio based on market conditions while also ensuring tax efficiency. It uses the yield curve inversion and price change indicators to allocate between risk and defensive assets. |
|[Commodities for the Long Run?](https://blogs.cfainstitute.org/investor/2024/07/08/commodities-for-the-long-run/)|CFA Institute Research Foundation|Pragmatic Asset Allocation is a tactical strategy that adjusts the portfolio based on market conditions while also ensuring tax efficiency. It uses the yield curve inversion and price change indicators to allocate between risk and defensive assets. |
|[Managed Futures versus Market-Neutral Multi-Factor Investing](https://insights.finominal.com/research-managed-futures-versus-market-neutral-multi-factor-investing)|MyAlgoAI|Pragmatic Asset Allocation is a tactical strategy that adjusts the portfolio based on market conditions while also ensuring tax efficiency. It uses the yield curve inversion and price change indicators to allocate between risk and defensive assets. |
|[Commodities for the Long Run?](https://blogs.cfainstitute.org/investor/2024/07/08/commodities-for-the-long-run/)|CFA Institute Research|Pragmatic Asset Allocation is a tactical strategy that adjusts the portfolio based on market conditions while also ensuring tax efficiency. It uses the yield curve inversion and price change indicators to allocate between risk and defensive assets. |
|[Classifying hedge fund strategies once again](http://mrzepczynski.blogspot.com/2024/07/classifying-hedge-fund-strategies-once.html)|The name of the blog or website is not mentioned in the given content.|Pragmatic Asset Allocation is a tactical strategy that adjusts the portfolio based on market conditions while also ensuring tax efficiency. It uses the yield curve inversion and price change indicators to allocate between risk and defensive assets. |
|[When Rebalancing Creates Higher Returns-and When It Doesn’t](https://www.morningstar.com/columns/rekenthaler-report/when-rebalancing-creates-higher-returnsand-when-it-doesnt)|Morningstar|Pragmatic Asset Allocation is a tactical strategy that adjusts the portfolio based on market conditions while also ensuring tax efficiency. It uses the yield curve inversion and price change indicators to allocate between risk and defensive assets. |


### coding

|Title|Source|Summary|
|-----|-------|----------|
|[How to trade a covered call with Alpaca (the easy way)](https://pyquantnews.com/the-pyquant-newsletter/how-to-trade-a-covered-call-with-alpaca)|Alpaca|Learn how to trade a covered call using Alpaca's Trading API with Python. Execute trades, manage positions, and automate trading strategies with Alpaca's powerful platform. |
|[Quickly make a trading strategy with a 82% win rate](https://pyquantnews.com/the-pyquant-newsletter/quickly-make-a-trading-strategy-with-a-82-win-rate)|Quantifiable Edges|Learn how to trade a covered call using Alpaca's Trading API with Python. Execute trades, manage positions, and automate trading strategies with Alpaca's powerful platform. |
|[Portfolio Hedging with Put Options](https://robotwealth.com/portfolio-hedging-with-put-options/)|Robot Wealth|Learn how to trade a covered call using Alpaca's Trading API with Python. Execute trades, manage positions, and automate trading strategies with Alpaca's powerful platform. |
|[Python Protocols: Leveraging Structural Subtyping](https://realpython.com/python-protocol/)|Towards Data Science|Learn how to trade a covered call using Alpaca's Trading API with Python. Execute trades, manage positions, and automate trading strategies with Alpaca's powerful platform. |


### economics

|Title|Source|Summary|
|-----|-------|----------|
|[Unexpected Economist: Carl Linnaeus on Economic Theory](https://conversableeconomist.com/2024/07/16/unexpected-economist-carl-linnaeus-on-economic-theory/)|Conversable Economist|Carl Linnaeus believed that every country possessed the natural resources necessary for a multifunctional economy. He supported state interventionism and favored autarky, but also believed in the potential of transmutationist botany for economic prosperity. |
|[Recession Probabilities for June 2025](https://econbrowser.com/archives/2024/07/recession-probabilities-for-june-2025)|NBER|Carl Linnaeus believed that every country possessed the natural resources necessary for a multifunctional economy. He supported state interventionism and favored autarky, but also believed in the potential of transmutationist botany for economic prosperity. |
|[Yield Curve Control Means The Party Can Continue, What's Not To Love?](http://climateerinvest.blogspot.com/2024/07/yield-curve-control-means-party-can.html)|Climateer Investing|Carl Linnaeus believed that every country possessed the natural resources necessary for a multifunctional economy. He supported state interventionism and favored autarky, but also believed in the potential of transmutationist botany for economic prosperity. |


### fundamental

|Title|Source|Summary|
|-----|-------|----------|
|[China Economic Sentiment](https://econbrowser.com/archives/2024/07/china-economic-sentiment)|Econbrowser|Torsten Slok's slide deck shows graphs illustrating the impact of the real estate market collapse on China's economy, supporting the interpretation of manipulated Chinese economic statistics. |


### tech

|Title|Source|Summary|
|-----|-------|----------|
|[Goldman Sachs Throws Cold Water on AI Mania](https://www.institutionalinvestor.com/article/2di0s1e6m7h197mfh6fb4/portfolio/goldman-sachs-throws-cold-water-on-ai-mania)|Goldman Sachs|Goldman Sachs warns that AI may not live up to its promises, citing high costs and lack of productivity gains. MIT professor and Silicon Valley veteran Roger McNamee raise similar concerns. |


### asset-management

|Title|Source|Summary|
|-----|-------|----------|
|[How Much Money You Need For Retirement](https://awealthofcommonsense.com/2024/07/how-much-money-you-need-for-retirement/)|The name of the blog or website is "A Wealth of Common Sense".|The 4% rule for retirement may not be widely followed, but it is conservative and has historical evidence to support it. It's a good estimate to use when planning for retirement. |
